version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"  # RabbitMQ port
      - "15672:15672" # RabbitMQ management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 10s
      retries: 3

  consumer:
    image: lahav97/orderservice:latest
    container_name: consumer
    ports:
      - "5099:5099"  # Map local port 5099 to container's internal port 5099
    environment:
      - ASPNETCORE_URLS=http://+:5099  # Matches the port in the consumer Dockerfile
      - RABBITMQ_HOST=rabbitmq  # Pointing to RabbitMQ container
    depends_on:
      rabbitmq:
        condition: service_healthy

  publisher:
    image: lahav97/cartservice:latest
    container_name: publisher
    ports:
      - "5252:5252"  # Map local port 5252 to container's internal port 5252
    environment:
      - ASPNETCORE_URLS=http://+:5252  # Matches the port in the publisher Dockerfile
      - RABBITMQ_HOST=rabbitmq  # Pointing to RabbitMQ container
    depends_on:
      rabbitmq:
        condition: service_healthy
